services:
  postgres:
    image: postgres:14-alpine
    container_name: authify-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-your_username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_password}
      POSTGRES_DB: ${DB_NAME:-authify_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - authify-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-your_username}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: authify-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - authify-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # 可选：添加 pgAdmin 用于数据库管理
  pgadmin:
    image: dpage/pgadmin4
    container_name: authify-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - authify-network

networks:
  authify-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
